[package]
name = "pineapple_data_structures"
version = "0.1.0"
authors = ["Matthew McMillian <matthewgmcmillian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
